### ISSUE TITLE
Is supposed to work on IITCm ? 

### ISSUE THREAD

**Issue by davidlinse** [Hurqalia/ontheroad#2]
This is a really nice plugin and works perfectly on desktop, but did not work for me on IITCm.
So, referring to the title.. 

* Is this supposed to work on IITCm too ? and
* can _we_ have this on mobile, in case it's not supported yet  ?

best regards
~david

**Comment by Hurqalia** [comment]
Hi David, 

It works on mobile.

![photo5832712987406870678](https://cloud.githubusercontent.com/assets/13137131/22828126/eb0c7f24-ef9b-11e6-9fda-c5f938d28d54.jpg)
![photo5832712987406870677](https://cloud.githubusercontent.com/assets/13137131/22828127/ee883bc0-ef9b-11e6-968d-633d04e985f9.jpg)
![photo5832712987406870676](https://cloud.githubusercontent.com/assets/13137131/22828131/f0ef2d38-ef9b-11e6-9ff0-e9668c09e214.jpg)
