### ISSUE TITLE
route share is broken

### ISSUE THREAD

**Issue by nhamer** [Hurqalia/ontheroad#3]
The url produced for maps is malformed, the url contains the function definitions for lat and lng rather than the actual lat/lng. Fix thus:

    window.plugin.ontheroad.exportRoute = function() {
		var rid = $('#route-exporter').attr('data-route-id');
		if (rid === '') {
			return;
		}

		var url_params = window.plugin.ontheroad.routes[rid].request.origin.lat() + ',' + window.plugin.ontheroad.routes[rid].request.origin.lng();

		if (window.plugin.ontheroad.routes[rid].request.waypoints.length > 0) {
			$.each(window.plugin.ontheroad.routes[rid].request.waypoints, function(wid, wroute) {
				url_params += '/' + wroute.location.lat() + ',' + wroute.location.lng();
			});
		}

		url_params += '/' + window.plugin.ontheroad.routes[rid].request.destination.lat() + ',' + window.plugin.ontheroad.routes[rid].request.destination.lng();

		var gmap_url = 'https://www.google.com/maps/dir/' + url_params;

		if (typeof android !== 'undefined' && android && android.intentPosLink) {
			return; // currently not available
		} else {
			window.open(gmap_url, '_blank');
		}
	};

**Comment by Hurqalia** [comment]
Thx nhamer, code commited ;-)
